$('.owl-carousel').owlCarousel({
    loop:true,
    margin:13.5,
    responsiveClass:true,
    responsive:{
        0:{
            items:1,
            nav:false
        },
        420:{
            items:2,
            nav: false
    },
        600:{
            items:3,
            nav:false
        },
        1000:{
            items:5,
            nav:false,
            loop:false
        }
    }
})